services:
  webserver:
    container_name: webserver
    build:
      context: ./docker/nginx
      args:
        UID: 1000
    ports:
      - 8080:80
    volumes:
      - ./public:/app/public
    networks:
      - app-network
    depends_on:
      - php-fpm

  php-fpm:
    container_name: php-fpm
    build:
      context: ./docker/php
      args:
        UID: 1000
    volumes:
      - ./:/app
      - ./docker/php/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini # variables de entorno para xdebug en windows
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    environment:
      XDEBUG_CLIENT_HOST: host.docker.internal  # ip del kernel de docker en windows (funciona tambien en mac)
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=DOCKER
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - database-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  database-data:

networks:
  app-network:
    external: true