version: '3.5'
services:
    app:
        build: ./docker/php
        volumes:
            - ./:/app
        working_dir: /app

    webserver:
        image: nginx:latest
        ports:
            - 8000:80
        volumes: 
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    
    db:
        image: mysql:5.7
        ports:
            - 3306:3306
        environment: 
            - MYSQL_ROOT_PASSWORD=toor
            - MYSQL_DATABASE=db
        volumes: 
            - symfony-data:/var/lib/mysql

volumes: 
    symfony-data: